---
title: "Trabalho Controle de Qualidade"
output: html_document
---

site de referencia
https://rpubs.com/adelmofilho/post4#:~:text=Gr%C3%A1ficos%20X%2Dbarra%20e%20R,-Para%20a%20constru%C3%A7%C3%A3o&text=A%20constru%C3%A7%C3%A3o%20de%20todos%20gr%C3%A1ficos,exemplo%2C%20com%20o%20seguinte%20c%C3%B3digo.

```{r}
install.packages("qcc")
library(qcc)
```


```{r}
dados <- read.csv("Grupo 5.csv",header = T, dec = ",", sep = ";")
dados2 <- read.csv("Grupo 5  -  2.csv",header = T, dec = ",", sep = ";")
dados
dados2
```

#Gráficos de Controle
```{r}
plot.xbar = qcc(dados2, type="xbar")
plot.R = qcc(dados2, type="R")
```


#Análise de Capacidade 
```{r}
process.capability(object = plot.xbar,
                   spec.limits=c(6,9))
```


#Avaliação do Sistema de Medição
```{r}
r=(dados2$Mesure.1-dados2$Mesure.2)

rb=c(mean(r[1:5]),mean(r[6:10]),mean(r[11:15]))
sigrepe=mean(rb)/1.128
xbb=c(mean(dados$Response[1:10]),mean(dados$Response[11:20]),mean(dados$Response[21:30]))
rxbb=range(xbb)[2]-range(xbb)[1]
sigrepro=sqrt((rxbb/1.693)**2-(sigrepe**2)/(5*2))
```

